server:
  port: 7001

info:
  app:
    name: Deploy Azure Pipelines
    description: Aplicação para demonstrar deploy Azure Pipeline
    version: 1.0.0

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: health, info, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true