server:
  port: 7001
info:
  app:
    name: Spring Demo Azure Pipeline
    description: Aplicação para demonstração de deploy no Azure
    version: 1.0.0


management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /management
      exposure:
        include: health, info, prometheus, env, flyway
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    env:
      enabled: true
    prometheus:
      enabled: true
    flyway:
      enabled: true